# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trafiq.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trafiq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctrafiq.proto\"6\n\tInputUser\x12\r\n\x05ville\x18\x01 \x01(\t\x12\x0b\n\x03\x62us\x18\x02 \x01(\t\x12\r\n\x05\x61rret\x18\x03 \x01(\t\"9\n\x0cOutputServer\x12\x15\n\rtemps_initial\x18\x01 \x01(\t\x12\x12\n\ntemps_reel\x18\x02 \x01(\t28\n\rTrafiqService\x12\'\n\x08GetInput\x12\n.InputUser\x1a\r.OutputServer\"\x00\x42\x05Z\x03./pb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trafiq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\003./p'
  _globals['_INPUTUSER']._serialized_start=16
  _globals['_INPUTUSER']._serialized_end=70
  _globals['_OUTPUTSERVER']._serialized_start=72
  _globals['_OUTPUTSERVER']._serialized_end=129
  _globals['_TRAFIQSERVICE']._serialized_start=131
  _globals['_TRAFIQSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
