// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: trafiq.proto

package p

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ville         string                 `protobuf:"bytes,1,opt,name=ville,proto3" json:"ville,omitempty"`
	Bus           string                 `protobuf:"bytes,2,opt,name=bus,proto3" json:"bus,omitempty"`
	Arret         string                 `protobuf:"bytes,3,opt,name=arret,proto3" json:"arret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputUser) Reset() {
	*x = InputUser{}
	mi := &file_trafiq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputUser) ProtoMessage() {}

func (x *InputUser) ProtoReflect() protoreflect.Message {
	mi := &file_trafiq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputUser.ProtoReflect.Descriptor instead.
func (*InputUser) Descriptor() ([]byte, []int) {
	return file_trafiq_proto_rawDescGZIP(), []int{0}
}

func (x *InputUser) GetVille() string {
	if x != nil {
		return x.Ville
	}
	return ""
}

func (x *InputUser) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

func (x *InputUser) GetArret() string {
	if x != nil {
		return x.Arret
	}
	return ""
}

type OutputServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TempsInitial  string                 `protobuf:"bytes,1,opt,name=temps_initial,json=tempsInitial,proto3" json:"temps_initial,omitempty"`
	TempsReel     string                 `protobuf:"bytes,2,opt,name=temps_reel,json=tempsReel,proto3" json:"temps_reel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputServer) Reset() {
	*x = OutputServer{}
	mi := &file_trafiq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputServer) ProtoMessage() {}

func (x *OutputServer) ProtoReflect() protoreflect.Message {
	mi := &file_trafiq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputServer.ProtoReflect.Descriptor instead.
func (*OutputServer) Descriptor() ([]byte, []int) {
	return file_trafiq_proto_rawDescGZIP(), []int{1}
}

func (x *OutputServer) GetTempsInitial() string {
	if x != nil {
		return x.TempsInitial
	}
	return ""
}

func (x *OutputServer) GetTempsReel() string {
	if x != nil {
		return x.TempsReel
	}
	return ""
}

var File_trafiq_proto protoreflect.FileDescriptor

const file_trafiq_proto_rawDesc = "" +
	"\n" +
	"\ftrafiq.proto\"I\n" +
	"\tInputUser\x12\x14\n" +
	"\x05ville\x18\x01 \x01(\tR\x05ville\x12\x10\n" +
	"\x03bus\x18\x02 \x01(\tR\x03bus\x12\x14\n" +
	"\x05arret\x18\x03 \x01(\tR\x05arret\"R\n" +
	"\fOutputServer\x12#\n" +
	"\rtemps_initial\x18\x01 \x01(\tR\ftempsInitial\x12\x1d\n" +
	"\n" +
	"temps_reel\x18\x02 \x01(\tR\ttempsReel28\n" +
	"\rTrafiqService\x12'\n" +
	"\bGetInput\x12\n" +
	".InputUser\x1a\r.OutputServer\"\x00B\x05Z\x03./pb\x06proto3"

var (
	file_trafiq_proto_rawDescOnce sync.Once
	file_trafiq_proto_rawDescData []byte
)

func file_trafiq_proto_rawDescGZIP() []byte {
	file_trafiq_proto_rawDescOnce.Do(func() {
		file_trafiq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trafiq_proto_rawDesc), len(file_trafiq_proto_rawDesc)))
	})
	return file_trafiq_proto_rawDescData
}

var file_trafiq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trafiq_proto_goTypes = []any{
	(*InputUser)(nil),    // 0: InputUser
	(*OutputServer)(nil), // 1: OutputServer
}
var file_trafiq_proto_depIdxs = []int32{
	0, // 0: TrafiqService.GetInput:input_type -> InputUser
	1, // 1: TrafiqService.GetInput:output_type -> OutputServer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trafiq_proto_init() }
func file_trafiq_proto_init() {
	if File_trafiq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trafiq_proto_rawDesc), len(file_trafiq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trafiq_proto_goTypes,
		DependencyIndexes: file_trafiq_proto_depIdxs,
		MessageInfos:      file_trafiq_proto_msgTypes,
	}.Build()
	File_trafiq_proto = out.File
	file_trafiq_proto_goTypes = nil
	file_trafiq_proto_depIdxs = nil
}
